postgres:
    dialect: postgres
    datasource: dbname=test sslmode=disable
    dir: test-migrations

mysql:
    dialect: mysql
    datasource: root@/test?parseTime=true
    dir: test-migrations

mysql_noflag:
    dialect: mysql
    datasource: root@/test
    dir: test-migrations

mysql_env:
    dialect: mysql
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true
    dir: test-migrations

mysql_ssl:
    dialect: mysql
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true&tls=custom
    dir: test-migrations
    tls:
        ca: ${MYSQL_CA_CERT_FILE}
        cert: ${MYSQL_CLIENT_CERT_FILE}
        key: ${MYSQL_CLIENT_KEY_FILE}

sqlite:
    dialect: sqlite3
    datasource: test.db
    dir: test-migrations
    table: migrations
